### ISSUE TITLE
Incompatibility with HandyNotes: DungeonLocations

### ISSUE THREAD

**Issue by Redux28** [Dathwada/handynotes-valdrakken#7]
Hi, first thank you for this great add-on. I'm having the issue that when both HandyNotes: DungeonLocations and HandyNotes: Valdrakken are active, the icons for DungeonLocations are invisible in any _continent_ map (Tooltip does shows when you mouse over the expected location).

Second issue is that there doesn't seem to be an option as stated on the add-on description to show only character professions.

**Comment by Dathwada** [comment]
Hi, I tested [HandyNotes_DungeonLocations](https://www.curseforge.com/wow/addons/handynotes_dungeonlocations) with my addon [HandyNotes: Valdrakken](https://www.curseforge.com/wow/addons/handynotes-valdrakken) and I am not having this issues.

And there is an option to show only character professions in this addon.
![](https://user-images.githubusercontent.com/57680823/228561539-12013593-843f-4ec6-a1ab-2eab4719ccd7.png)

BUT, I teset [HandyNotes_DungeonLocations](https://www.curseforge.com/wow/addons/handynotes_dungeonlocations) against the other [Handynotes_Valdrakken](https://www.curseforge.com/wow/addons/handynotes_valdrakken) addon and with this I also have the issues you mentioned.

**Comment by Redux28** [comment]
OH!
Totally my bad, i don't know exactly how but i ended with the other Valdrakken addon installed but WowUP showing it was this one installed. I removed the addon and reinstalled this one and now everything is working like it's supposed to.

Thank you very much for your time.
